# Travis-CI Build for Boo
# see travis-ci.org for details

language: csharp

# Choose a compatible Mono version
mono:
  - 4.2.1

env:
  global:
    # GITHUB_TOKEN=xxxx
    - secure: "Nk6IRV4woRpCk3D/6oVTpAfDRPQnxEBdJN9955X/mtDPLuw/lSYFEKOhIc9LQ29fcCGyQPS1eb+rhCAFsqlOGfhkWWb1whnMGCahi2uXP7naCg3rg7A1HeNY/JcuR+xXgQDQmdbm7aiI9IG0Z2vOIXNQhCuR9j/a8wpEdwrJ8/k="
    - EnableNuGetPackageRestore=true
    - NUNIT_VERSION="2.6.3"
    - NANT_COMMIT="e3644541bf083d8e33f450bfbd1a4147e494769c"
    - MONO_PATH=mono
    - MCS_PATH=mcs

install:
  - ./build-tools/bootstrap

script:
 - ./ci

after_success:
 # Generate a simple distribution file
 - popd
 - cp -r build boo-alpha
 - zip boo-alpha.zip boo-alpha/*
 - mono --debug build/booi.exe scripts/github-release.boo -- alpha boo-alpha.zip

# Notify development list when needed
notifications:
 recipients:
   - boolang@googlegroups.com
 email:
   on_success: change
   on_failure: always
